name: Update Ranking

on:
  pull_request:
    types: [closed]

jobs:
  update-ranking:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Run ranking update script
        run: python scripts/update_ranking.py

      - name: Commit and push updated ranking
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add RANKING.md
          git commit -m "🔄 Auto-update ranking"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}